# 전역 변수 초기화
drawdate_str = ""
thickness = 0
T5_is =""
OP = 0
OPH = 0
KPH = 0
TRH = 0
br = 0   # bending rate 연신율

saved_DimXpos = 0
saved_DimYpos = 0
saved_Xpos = 0
saved_Ypos = 0
saved_direction = "up"
saved_text_height = 0.28
saved_text_gap = 0.05
dimdistance = 0
dim_horizontalbase = 0
dim_verticalbase = 0
distanceXpos = 0
distanceYpos = 0
start_time = 0
secondord = None
drawdate_str = None
company = None
workplace = None
drawnby = None
issuedate = None
usage = None
openType = None
person = None
SU = None
carOP = None
carOPH = None
KH = None
FH = None
Material = None
Spec = None
thickness_string = None
Vcut = None
doorDevice = None
CW = None
CD = None
CH = None
ph = None
CPH = None
SIDE = None
REAR = None
WF = None
WS = None
WSM = None
WR = None
WRM = None
trimMaterial = None
TR1 = None
TR2 = None
TR3 = None
TR4 = None
TR5 = None
TR6 = None
P1_material, P1_width, P1_widthReal, P1_holegap, P1_hole1, P1_hole2, P1_hole3, P1_hole4, P1_COPType = None,None,None,None,None,None,None,None,None
P2_material, P2_width, P2_widthReal, P2_holegap, P2_hole1, P2_hole2, P2_hole3, P2_hole4, P2_COPType= None,None,None,None,None,None,None,None,None
P3_material, P3_width, P3_widthReal, P3_holegap, P3_hole1, P3_hole2, P3_hole3, P3_hole4, P3_COPType= None,None,None,None,None,None,None,None,None
P4_material, P4_width, P4_widthReal, P4_holegap, P4_hole1, P4_hole2, P4_hole3, P4_hole4, P4_COPType= None,None,None,None,None,None,None,None,None
P5_material, P5_width, P5_widthReal, P5_holegap, P5_hole1, P5_hole2, P5_hole3, P5_hole4, P5_COPType= None,None,None,None,None,None,None,None,None
P6_material, P6_width, P6_widthReal, P6_holegap, P6_hole1, P6_hole2, P6_hole3, P6_hole4, P6_COPType= None,None,None,None,None,None,None,None,None
P7_material, P7_width, P7_widthReal, P7_holegap, P7_hole1, P7_hole2, P7_hole3, P7_hole4, P7_COPType= None,None,None,None,None,None,None,None,None
P8_material, P8_width, P8_widthReal, P8_holegap, P8_hole1, P8_hole2, P8_hole3, P8_hole4, P8_COPType= None,None,None,None,None,None,None,None,None
P9_material, P9_width, P9_widthReal, P9_holegap, P9_hole1, P9_hole2, P9_hole3, P9_hole4, P9_COPType= None,None,None,None,None,None,None,None,None
P10_material, P10_width, P10_widthReal, P10_holegap, P10_hole1, P10_hole2, P10_hole3, P10_hole4, P10_COPType= None,None,None,None,None,None,None,None,None
P11_material, P11_width, P11_widthReal, P11_holegap, P11_hole1, P11_hole2, P11_hole3, P11_hole4, P11_COPType= None,None,None,None,None,None,None,None,None

COP_bottomHeight=None
COP_centerdistance=None
COP_width=None
COP_Height=None
COP_holegap=None
COP_RibType=None
HOP_bottomHeight=None
HOP_width=None
HOP_Height=None
HOP_holegap=None
HOP_RibType=None
HRType=None
handrail_height=None
handrailSidegap1=None
handrailSidegap2=None
handrailSidegap3=None
handrailSidegap4=None
handrailSidegap5=None
HRFrontHolesize=None
handrailReargap1=None
handrailReargap2=None
handrailReargap3=None
handrailReargap4=None
handrailReargap5=None
HRRearHolesize=None
KP_material=None
TR_OP=None
TR_TRH=None
TR_upperhole1=None
TR_upperhole2=None
TR_upperhole3=None
TR_upperhole4=None
TR_material=None
CPIType=None
CPIHoleWidth=None
CPIHoleHeight=None
CPIholegap=None
CPIHeight=None
updateCPIHoleWidth=None
updateCPIHoleHeight=None
updateCPIholegap=None
updateCPIHeight=None
COL_Height=None
column_thickness=None
column_width=None
COL_FH=None
COL_Material=None
column_BottomHoleHorizontal=None
column_BottomHoleVertical=None
ELB_BottomHeight=None
ELB_BoxHorizontal=None
ELB_BoxVertical=None
ELB_RibType=None
CartP_Type=None       
CartP_Height=None
CartP_holegap1=None
CartP_holegap2=None
CartP_holegap3=None
CartP_holegap4=None
CartP_holegap5=None
CartP_HoleSize=None
panel_width=None
